#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O eDP-1 HDMI-1

bspc monitor eDP-1 -d I II III IV V VI VII
bspc monitor HDMI-1 -d  VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
# bspc rule -a mpv state=floating

#
## my stuff
#

killall polybar
polybar &

killall batsignal
batsignal &

killall nm-applet
nm-applet &

#autorandr --change &

xsetroot -cursor_name left_ptr

