[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
normal = { family = "Iosevka" }
size = 8

[window]
opacity = 0.3

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]
